swagger: "2.0"
info:
  description: ""
  version: "1.0.0"
  title: "Lingogame"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
# host: ""
basePath: "/v2"
tags:
  - name: "word"
    description: "Lingo words"

schemes:
  - "https"
  - "http"
paths:
  /word:
    post:
      tags:
        - "word"
      summary: "Add a new word"
      description: ""
      operationId: "addWord"
      consumes:
        - "application/json"
        - "application/xml"
      produces:
        - "application/xml"
        - "application/json"
      parameters:
        - in: "path"
          name: "word"
          description: "Word object that needs to be added to the store"
          required: true
          type: "string"
      responses:
        "200":
          description: "Successful operation"
          schema:
            $ref: "#/definitions/Word"
        "400":
          description: "Invallid word"
        "405":
          description: "Invalid input"

definitions:
  Word:
    type: "object"
    required:
      - "word"
      - "letterCount"
    properties:
      id:
        type: "integer"
        format: "int64"
      word:
        type: "string"
    xml:
      name: "Word"
