name: PMD Source Code Analyzer on Push

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  pmd:
    name: PMD
    runs-on: ubuntu-latest

    steps:
      - uses: sfdx-actions/setup-pmd@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: run-pmd
        run: pmd -d ./force-app/main/default/classes -R category/apex/design.xml -f text
